version: '3.5'

services:

  keycloak:
    image: quay.io/keycloak/keycloak-x:16.1.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    container_name: keycloak
    volumes:
      - ./certs/keycloak.key:/etc/x509/https/tls.key
      - ./certs/keycloak.crt:/etc/x509/https/tls.crt
      - ./certs/rootCA.crt:/tmp/certs/ca.crt
      - ./keycloak/export:/tmp/realm-config
    command:
      [
        # Database:
        # '-Dkc.db=mariadb',
        # '-Dkc.db.url.host=mariadb',
        # '-Dkc.db.username=keycloak',
        # '-Dkc.db.password=password',

        # Hostname:
        # Hostname to be set is strict hostname is enabled
        #'-Dkc.hostname.strict=false',

        # HTTP/TLS:
        # Insecure requests are disabled by default in production
        #'-Dkc.http.enabled=true',
        # '-Dkc.hostname.strict-https=false',
        #'-Dkc.https.certificate.file=/etc/x509/https/tls.crt',
        #'-Dkc.https.certificate.key-file=/etc/x509/https/tls.key',

        # 'start-dev'
        'start',
        '--auto-build --db=mariadb --db-url-host=mariadb --db-username=keycloak --db-password=password --hostname-strict=false --http-enabled=true'
      ]
    networks:
      - keycloak-network
    ports:
      # HTTP
      - 8080:8080
      # HTTPS
      - 8443:8443
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5.5
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    container_name: keycloak-mariadb
    # healthcheck:
    #     test: ['CMD', 'mysqladmin', 'ping', '--silent']
    networks:
      - keycloak-network
    volumes:
      - vol-mariadb:/var/lib/mysql

  js-console:
    build: ./js-console
    image: js-console
    ports:
      - 8000:80
    container_name: keycloak-js-console
    # For debugging
    # volumes:
    #   - ./js-console/src/index.html:/usr/share/nginx/html/index.html
    #   - ./js-console/src/keycloak.json:/usr/share/nginx/html/keycloak.json
    #   - ./js-console/src/KeycloakSilent.js:/usr/share/nginx/html/KeycloakSilent.js
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: local

volumes:
  vol-mariadb:
