version: '3.5'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_DB=mariadb
      - KC_DB_URL_HOST=mariadb
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/server.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/server.key
      # If behind a proxy
      # - KC_PROXY=edge
    container_name: keycloak
    volumes:
      - ./certs/keycloak.key:/etc/x509/server.key
      - ./certs/keycloak.crt:/etc/x509/server.crt
      - ./certs/rootCA.crt:/tmp/certs/ca.crt
      - ./keycloak/export:/tmp/realm-config
    command:
      [
        # Following will start in dev-mode
        # 'start-dev'
        # Alternative use following explicit flags for auto-build
        'start',
        '--auto-build',
        # '--log-level=trace',
        '--http-enabled=true --hostname-strict=false --hostname-strict-https=false'
      ]
    networks:
      - keycloak-network
    ports:
      # HTTP
      - 8080:8080
      # HTTPS
      - 8443:8443
    depends_on:
      - mariadb

  # keycloak-prebuilt:
  #   build: ./keycloak
  #   image: keycloak-prebuilt
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=password
  #     - KC_DB_URL_HOST=mariadb
  #     - KC_DB_USERNAME=keycloak
  #     - KC_DB_PASSWORD=password
  #     - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/server.crt
  #     - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/server.key
  #     # If behind a proxy (KC_HOSTNAME need to be set as well)
  #     # - KC_PROXY=edge
  #     # - KC_HOSTNAME=localhost:8443
  #     # Following not required if KC_PROXY is set to `edge`
  #     - KC_HTTP_ENALBED=true
  #     - KC_HOSTNAME_STRICT=false
  #     - KC_HOSTNAME_STRICT_HTTPS=false
  #   container_name: keycloak
  #   volumes:
  #     - ./certs/keycloak.key:/etc/x509/server.key
  #     - ./certs/keycloak.crt:/etc/x509/server.crt
  #     - ./certs/rootCA.crt:/tmp/certs/ca.crt
  #     - ./keycloak/export:/tmp/realm-config
  #   networks:
  #     - keycloak-network
  #   ports:
  #     # HTTP
  #     - 8080:8080
  #     # HTTPS
  #     - 8443:8443
  #   depends_on:
  #     - mariadb

  mariadb:
    image: mariadb:10.5.5
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    container_name: keycloak-mariadb
    # healthcheck:
    #     test: ['CMD', 'mysqladmin', 'ping', '--silent']
    networks:
      - keycloak-network
    volumes:
      - vol-mariadb:/var/lib/mysql

  js-console:
    build: ./js-console
    image: js-console
    ports:
      - 8000:80
    container_name: keycloak-js-console
    # For debugging
    # volumes:
    #   - ./js-console/src/index.html:/usr/share/nginx/html/index.html
    #   - ./js-console/src/keycloak.json:/usr/share/nginx/html/keycloak.json
    #   - ./js-console/src/KeycloakSilent.js:/usr/share/nginx/html/KeycloakSilent.js
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: local

volumes:
  vol-mariadb:
