version: '3.5'

services:

  keycloak:
    image: jboss/keycloak:11.0.3
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_ADDR=mariadb
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - DB_VENDOR=mariadb
    container_name: keycloak
    volumes:
      - ./keycloak/export:/tmp/realm-config
    command:
      [
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/tmp/realm-config',
        '-Dkeycloak.migration.strategy=IGNORE_EXISTING',
      ]
    networks:
      - keycloak-network
    ports:
      # HTTP
      - 8080:8080
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5.5
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    container_name: keycloak-mariadb
    networks:
      - keycloak-network
    volumes:
      - vol-mariadb:/var/lib/mysql

  js-console:
    build: ./js-console
    image: js-console
    ports:
      - 8000:80
    container_name: keycloak-js-console
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: local

volumes:
  vol-mariadb:
